project3/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    #sessions: 'users/sessions',
    registrations: 'users/registrations',
    #passwords: 'users/passwords',
    #confirmations: 'users/confirmations',
    #unlocks: 'users/unlocks',
    #omniauth: 'users/omniauth'
  }
  
  get 'events/:event_id/rsvps/export', :to => 'rsvps#export', :as => 'export_event_rsvps'
  get 'events/:event_id/rsvps/edit', :to => 'rsvps#edit', :as => 'edit_user_event_rsvp_list'
  get 'events/:event_id/attendance', :to => 'events#attendance', :as => 'event_attendance_list'
  get 'users/:user_id/events/:event_id/rsvps/export', :to => 'rsvps#export', :as => 'export_user_event_rsvps'
  get 'users/:user_id/events/:event_id/rsvps/edit', :to => 'rsvps#edit'
  get 'users/:user_id/events/:event_id/attendance', :to => 'events#attendance', :as => 'user_event_attendance_list'
  patch 'events_users_data/:id/update_attendance', :to => 'events_users_data#mark_attendance', :as => 'events_users_datum_update_attendance'
  get 'users/:user_id/events/:event_id/attendancescanner', :to => 'events#attendance_scanner', :as => 'user_event_attendance_scanner'
  post 'events/:event_id/attendancescan', :to => 'events#attendance_scan', :as => 'event_attendance_scan'

  resources :events do
    resources :rsvps do
      resources :events_users_data
    end
    resources :users
  end

  resources :users do
    resources :events do
      resources :rsvps
    end
  end

  resources :events_users_data
  resources :rsvps

  root "home#index"

end

project3/app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true
  has_one :event_user_datum

  def self.to_csv
    attributes = %w{name email user_role relation attending diet additional_persons num_babies num_toddlers require_carpark message attended}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |r|
        e = r.event_user_datum
        csv << [r.name, r.email, e.user_role, e.relation, e.attending, e.diet, e.additional_persons, e.num_babies, e.num_toddlers, e.require_carpark, e.message, e.attended]
      end
    end
  end
end

project3/app/controllers/rsvps_controller.rb
# frozen_string_literal: true

# Specifications
# ==============
# Rsvps have :event_id, :event_user_datum_id (pending), :name, :email, and :key
# :key is nil for users with an account

# Notes
# =====
# We use find_by_??? here so that a nil result can be returned instead of having Rails throw an error.
# To find a user by email: User.find_by_email(rsvp[:email])
# To find an event: Event.find_by_id(rsvp[:event_id])
# To find an event user datum: EventUserDatum.find_by_id(rsvp[:event_user_datum_id])

# Flow Control
# ============
# ../events/:event_id/rsvps
# [logged in, owner] rsvp list associated with the event
# [logged in, guest] redirect to rsvp if exists or root otherwise
# [not logged in, key] redirect to new/edit rsvp if key is valid or root otherwise
# [not logged in, no key] redirect to root

# ../events/:event_id/rsvps/:id
# [logged in, owner] show that particular rsvp response
# [logged in, guest] if not his own rsvp, redirect to his own rsvp if exists or root otherwise
# [not logged in, key or no key] redirect to root

# ../events/:event_id/rsvps/new
# [logged in, owner] form for creating new rsvps for event
# [logged in, guest] [not logged in] redirect to user_events (for guest) or root (otherwise)

# ../events/:event_id/rsvps/:id/edit
# [logged in, owner] edit the rsvp list
# [logged in, guest] edit his own response if rsvp belongs to him or redirect to root otherwise
# [not logged in, key] edit response
# [not logged in] redirect to root

# ../events/:event_id/rsvps/:id/update
# update a single invitation. AJAX call? (remote: true)

# ../events/:event_id/rsvps/:id/delete
# delete a single invitation. AJAX call? (remote: true)

# ../rsvps

# Q&A
# ===
# Question: What if the user signs up while having outstanding RSVPs?
# Proposal: Nothing. The check for RSVPs is done via email.

# Template code to account for the above directions
# =================================================
# case logged_in?
#   when true # ___LOGGED IN
#     @event = Event.find_by_id(params[:event_id])
#     case is_owner?(@event, current_user)
#       when true # ___IS OWNER
#         DO OWNER STUFF
#       when false
#         if is_invited?(@event, current_user) # ___IS GUEST
#           DO GUEST STUFF
#         else # ___IS NEITHER OWNER NOR GUEST
#           DO BAD STUFF
#         end
#       end
#   when false # ___NOT LOGGED IN
#     case key.nil?
#       when true # ___HAS NO KEY
#         DO BAD STUFF
#       when false # ___HAS KEY
#         @rsvp = Rsvp.find_by_key(params[:key])
#         if @rsvp.nil? # ___KEY IS INVALID
#           DO BAD STUFF
#         else # ___KEY IS VALID (i.e. USER DOES NOT EXIST IN SYSTEM YET)
#           DO STUFF
#         end
#       end
#   end

require 'bcrypt' # For encrypting the email + event_id for users without accounts
require 'csv' # For exporting RSVPs as a csv file for download
require 'rqrcode'

class RsvpsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :edit]
  def index
    case logged_in?
      when true # ___LOGGED IN
        @event = Event.find_by_id(params[:event_id]) 

        if @event.nil?
          redirect_to user_events_path(current_user)
          return
        end

        case is_owner?(@event, current_user)
          when true # ___IS OWNER
            @user_role = :owner
            @rsvps = @event.rsvps
          when false # ___IS GUEST
            if is_invited?(@event, current_user) 
              rsvp = @event.rsvps.find_by_email(current_user.email)
              redirect_to edit_user_event_rsvp_path(current_user, @event, rsvp)
              return
            else # ___IS NEITHER OWNER NOR GUEST
              redirect_to user_events_path(current_user)
              return
            end
          end

      when false # ___NOT LOGGED IN

        case key.nil?
          when true # ___HAS NO KEY
            redirect_to root_path
            return
          when false # ___HAS KEY
            rsvp = Rsvp.find_by_key(params[:key])
            if rsvp.nil? # ___KEY IS INVALID
              redirect_to root_path
              return
            else # ___KEY IS VALID (i.e. USER DOES NOT EXIST IN SYSTEM YET)
              redirect_to edit_rsvp_path(rsvp, key: params[:key], attending: params[:attending])
              return
            end
          end
      end
  end

  def show
    case logged_in?
      when true # ___LOGGED IN
        @event = Event.find_by_id(params[:event_id])
        case is_owner?(@event, current_user)
          when true # ___IS OWNER
            @rsvp = Rsvp.find_by_id(params[:id])
            @event_user_datum = @rsvp.event_user_datum
            @user_role = :owner
          when false
            if is_invited?(@event, current_user) # ___IS GUEST
              @rsvp = Rsvp.find_by_id(params[:id])
              #@user_event_datum = EventUserDatum.find_by_sql("SELECT * FROM event_user_data INNER JOIN rsvps ON event_user_data.rsvp_id = rsvps.id INNER JOIN events ON rsvps.event_id = events.id WHERE event_user_data.user_role = 'guest' AND rsvps.email = '#{current_user.email}'")
              if @rsvp[:email] == current_user[:email] # Check that the rsvp is indeed for the user
                @user_role = :guest
              else
                flash[:notice] = 'That invitation is not for you!'
                redirect_to user_events_path(current_user)
                return
              end
            else # ___IS NEITHER OWNER NOR GUEST
              flash[:notice] = 'Sorry but you weren\'t invited to that event!'
              redirect_to user_events_path(current_user)
              return
            end
          end
      when false # ___NOT LOGGED IN
        redirect_to root_path
        return
      end
  end

  def new
    case logged_in?
      when true # ___LOGGED IN
        @event = Event.find_by_id(params[:event_id])
        case is_owner?(@event, current_user)
          when true # ___IS OWNER
          when false
            redirect_to user_events_path(current_user)
            return
          end
      when false # ___NOT LOGGED IN
        redirect_to root_path
        return
      end
  end

  def create
    @event = Event.find(params[:event_id])
    rsvps = params[:rsvp].values.reject do |rsvp|
      rsvp.values.any? &:blank?
    end
    rsvps.each { |rsvp| 
      tmpstring = rsvp[:email] + rsvp[:event_id].to_s
      rsvp[:key] = BCrypt::Password.create(tmpstring).to_s
      tmp = Rsvp.create! rsvp
      tmp_event_user_datum = tmp.create_event_user_datum(user_role: :guest)
      if user_email_exists?(rsvp[:email]) 
        user = User.find_by_email(rsvp[:email])
        @event.users << user # ___creating invited user relation with event
        tmp.user_id = user.id # ___creating user id in Rsvp model
        tmp.save
      end
      tmp_event_user_datum.save
      RsvpMailer.with(sender: current_user.username, rsvp: tmp).rsvp_email.deliver_later
    }
    if rsvps.length > 0
      flash[:notice] = "Created #{rsvps.length} #{'invitation'.pluralize(rsvps.length)}"
    end
    redirect_to event_rsvps_path(@event)
    return
  end

  def edit
    case logged_in?
      when true # ___LOGGED IN
        @event = Event.find_by_id(params[:event_id])
        case is_owner?(@event, current_user)
          when true # ___IS OWNER
            @user_role = :owner
            @user = current_user
            @rsvps = Rsvp.where(:event_id => @event[:id])
          when false # ___IS GUEST
            if is_invited?(@event, current_user) 
              @user_role = :guest
              @rsvp = @event.rsvps.where(:email => current_user[:email]).first
              @event_user_datum = @rsvp.event_user_datum
              #the name of the creater of the event
              #@owner = @event.users.find_by_sql("SELECT username FROM users INNER JOIN rsvps ON users.id = rsvps.user_id INNER JOIN event_user_data ON rsvps.id = event_user_data.rsvp_id INNER JOIN events ON rsvps.event_id = events.id WHERE event_user_data.user_role = 'owner' AND events.id = #{params[:event_id]}")
              @owner = @event.users.where(event_user_data: EventUserDatum.where(user_role: 'owner')).first
            else # ___IS NEITHER OWNER NOR GUEST
              redirect_to user_events_path(current_user)
              return
            end
          end
      when false # ___NOT LOGGED IN
        case key.nil?
          when true # ___HAS NO KEY
            redirect_to root_path
          when false # ___HAS KEY
            @rsvp = Rsvp.find_by_key(params[:key])
            if @rsvp.nil? # ___KEY IS INVALID
              redirect_to root_path
              return
            else # ___KEY IS VALID (i.e. USER DOES NOT EXIST IN SYSTEM YET)
              @user_role = :guest
              @owner = @rsvp.event.users.where(event_user_data: EventUserDatum.where(user_role: 'owner')).first
              @event_user_datum = @rsvp.event_user_datum
            end
          end
      end
  end

  def update
    # Updates only a single record. Deal with this via AJAX?
    rsvp = Rsvp.find(params[:id])
    rsvp.update(rsvp_update_params)
    head :ok, :content_type => 'text/html'
  end

  def destroy
    # Deletes a single record. Deal with this via AJAX?
    @rsvp = Rsvp.find(params[:id])
    @rsvp.destroy
    # redirect_to root_path
    head :ok, :content_type => 'text/html'
  end

  def export
    rsvps = Rsvp.where(:event_id => params[:event_id])
    title = Event.find(params[:event_id]).title
    respond_to do |format|
      format.html { send_data rsvps.to_csv, filename: "#{title}-rsvps-#{Date.today}.csv" }
    end
  end

  private

  def user_email_exists?(email)
    User.where(:email => email).exists?
  end

  def logged_in?
    !current_user.nil?
  end

  def is_owner?(event, user)
    if event.nil? || user.nil?
      return false
    end
    #event.users.where(rsvps: event.event_user_data.where(user_role: "owner")).first == user

project3/app/helpers/rsvp_helper.rb
module RsvpHelper
end

project3/app/views/rsvps/_fields.html.erb
<fieldset>
    <%= fields_for :rsvp do |f| %>
        <div class="form-group row">
        <%= f.hidden_field :event_id, value: @event[:id], index: index %>

        <%= f.label :name, 'Name: ', index: index, :class => 'col-sm-1 col-form-label' %>
        <div class="col-sm-4"> <%= f.text_field :name, index: index, :class => 'form-control' %> </div>

        <%= f.label :email, 'Email: ', index: index, :class => 'col-sm-1 col-form-label' %>
        <div class="col-sm-4"> <%= f.email_field :email, index: index, :class => 'form-control' %> </div>
        </div>
    <% end %>
</fieldset>

project3/app/views/rsvps/edit.html.erb
<div style="width:100%;color:white;padding-top:3em;padding-left:10%;padding-right:10%">
<% if @user_role == :owner %>
        <h1>Invitation List</h1>
        <% @rsvps.each do |rsvp| %>
            <%= form_for rsvp, url: user_event_rsvp_path(@user, @event, rsvp), :remote => true, method: :patch, :class => 'form-inline' do |f| %>
                <div class="form-group row">
                    <%= f.label :name, 'Name: ', :class => 'col-sm-1 col-form-label' %> <div class="col-sm-4"> <%= f.text_field :name, :class => 'form-control' %> </div> <%= f.label :email, 'Email: ', :class => 'col-sm-1 col-form-label' %> <div class="col-sm-4"> <%= f.text_field :email, :readonly => true, :class => 'form-control' %> </div> <%= f.submit 'Update', :class => 'btn'%>
                </div>
            <% end %>
        <% end %>
        <%= form_tag event_rsvps_path do %>
            <%= render 'fields', index: 0 %>

            <%=
                button_tag 'Add invitation',
                type: 'button',
                id: 'add-invitation',
                data: { fields: render('fields', index: '__INDEX__').gsub('\n', '') },
                class: 'btn btn-outline-light'
            %>
            <%= submit_tag 'Submit', :class => 'btn btn-outline-light' %>
            <%= link_to 'Back to Events', user_events_path(@user), :class => "btn btn-outline-light" %>
        <% end %>
<% elsif @user_role == :guest %>
    <h1>RSVP from <%= @rsvp.name %> for <%= @rsvp.event.title %></h1>
    <% if params[:attending] == 'yes'%>
        <%= form_for @event_user_datum, url:events_users_datum_path(@event_user_datum), method: :patch do |form| %>
            <%= form.hidden_field :attending, value: 'Yes' %>

            <div class="form-group row">
                <%= form.label :relation, "Relationship with #{@owner.username}", :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"> <%= form.text_field :relation, :class => 'form-control' %> </div>
            </div>

            <div class="form-group row">
                <%= form.label :diet, 'Dietary Needs', :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"><%= form.text_field :diet, :class => 'form-control' %></div>
            </div>

            <div class="form-group row">
                <%= form.label :additional_persons, 'Number of Additional Persons', :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"><%= form.text_field :additional_persons, :class => 'form-control' %></div>
            </div>

            <div class="form-group row">
                <%= form.label :num_babies, 'Number of Babies', :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"><%= form.text_field :num_babies, :class => 'form-control' %></div>
            </div>

            <div class="form-group row">
                <%= form.label :num_toddlers, 'Number of Toddlers', :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"><%= form.text_field :num_toddlers, :class => 'form-control' %></div>
            </div>

            <div class="form-group row">
                <%= form.label :require_carpark, 'Parking lot needed?', :class => 'col-sm-4 col-form-label' %>
                <div class="col-sm-8"><%= form.select :require_carpark, options_for_select(['Yes', 'No']), {}, {:class => 'form-control'} %></div>
            </div>

            <div class="form-group row">
                <%= form.submit 'Update my response', :class => 'btn btn-outline-light'%>
            </div>
        <% end %>
    <% else %>
        <%= form_for @event_user_datum, url:events_users_datum_path(@event_user_datum), method: :patch do |form| %>
            <%= form.hidden_field :attending, value: 'No' %>
            <div class="form-group">
                <%= form.label :message, "Leave a message for #{@owner.username}? (Optional)", :class => 'col-sm-12 col-form-label' %><br>
                <%= form.text_area :message, :class => 'form-control' %>
            </div>

            <%= form.submit 'Update my response', :class => 'btn btn-outline-light'%>

        <% end %>
    <% end %>
<% end %>
</div>

project3/app/views/rsvps/index.html.erb
<div class="container container_rsvps_index">

    <div class="row row_rsvps_index">

            <div class="rsvps-grid-item1 col-sm-12">

                    <% if @user_role == :owner %>
                        <h41>All RSVPs for <%= @event.title %></h41>

                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Role</th>
                                    <th scope="col">Attending</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @rsvps.each.with_index(1) do |rsvp, index| %>
                                    <tr>
                                        <td scope="row"><%= index %></td>
                                        <td><%= rsvp.name.titleize %></td>
                                        <td><%= rsvp.email %></td>
                                        <td><%= rsvp.event_user_datum.user_role %></td>
                                        <td><%= rsvp.event_user_datum.attending %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
            </div>
    </div>
    <div class="row row_rsvps_index2">

            <div class="rsvps-grid-item2 col-sm-12">

                        <% if @rsvps.size > 0 %>
                            <%= link_to 'Edit', edit_user_event_rsvp_list_path(@event), :class => "btn btn-outline-light" %>
                        <% else %>
                            <%= link_to 'Add', new_event_rsvp_path(@event), :class => "btn btn-outline-light" %>
                        <% end %>
                        <%= link_to 'Back', user_events_path(current_user.id), :class => "btn btn-outline-light" %>

                        <% if @user.nil? %>
                            <%= link_to 'Export as CSV', export_event_rsvps_path, :class => "btn btn-outline-light" %>
                        <% elsif %>
                            <%= link_to 'Export as CSV', export_user_event_rsvps_path(current_user.id), :class => "btn btn-outline-light" %>
                        <% end %>
                    <% end %>

            </div>                
    </div>           
</div>

project3/app/views/rsvps/new.html.erb
<h1>New Invitation List</h1>

<%= form_tag event_rsvps_path do %>
<%= render 'fields', index: 0 %>

<%=
    button_tag 'Add invitation',
    type: 'button',
    id: 'add-invitation',
    data: { fields: render('fields', index: '__INDEX__').gsub('\n', '') }
%>
<%= submit_tag 'Submit' %>
<% end %>
<%= link_to 'Back', event_rsvps_path(@event) %>

project3/app/views/rsvps/show.html.erb
<div class="container_rsvps_show">

    <div class="row_rsvps_show">

        <div class="rsvps-grid-item3 col-sm-12">

                <h1>RSVP for <%= @event.title %> from <%= @rsvp.name %></h1>

                <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Attending</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td scope="row"><%= index %></td>
                                <td scope="row"><%= @rsvp.name %></td>
                                <td scope="row"><%= @rsvp.email %></td>
                                <td scope="row"><%= @event_user_datum.attending %></td>
                            </tr>
                        </tbody>
                </table>
        </div>
    </div>
</div>