project3/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    #sessions: 'users/sessions',
    registrations: 'users/registrations',
    #passwords: 'users/passwords',
    #confirmations: 'users/confirmations',
    #unlocks: 'users/unlocks',
    #omniauth: 'users/omniauth'
  }
  
  get 'events/:event_id/rsvps/export', :to => 'rsvps#export', :as => 'export_event_rsvps'
  get 'events/:event_id/rsvps/edit', :to => 'rsvps#edit', :as => 'edit_user_event_rsvp_list'
  get 'events/:event_id/attendance', :to => 'events#attendance', :as => 'event_attendance_list'
  get 'users/:user_id/events/:event_id/rsvps/export', :to => 'rsvps#export', :as => 'export_user_event_rsvps'
  get 'users/:user_id/events/:event_id/rsvps/edit', :to => 'rsvps#edit'
  get 'users/:user_id/events/:event_id/attendance', :to => 'events#attendance', :as => 'user_event_attendance_list'
  patch 'events_users_data/:id/update_attendance', :to => 'events_users_data#mark_attendance', :as => 'events_users_datum_update_attendance'
  get 'users/:user_id/events/:event_id/attendancescanner', :to => 'events#attendance_scanner', :as => 'user_event_attendance_scanner'
  post 'events/:event_id/attendancescan', :to => 'events#attendance_scan', :as => 'event_attendance_scan'

  resources :events do
    resources :rsvps do
      resources :events_users_data
    end
    resources :users
  end

  resources :users do
    resources :events do
      resources :rsvps
    end
  end

  resources :events_users_data
  resources :rsvps

  root "home#index"

end

project3/app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :rsvps, dependent: :destroy
    has_many :event_user_data, through: :rsvps, dependent: :destroy
end

project3/app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
    
    before_action :authenticate_user!#, :except => [ :show, :index ]

    def index
        if params[:user_id]
            @user = User.find(current_user.id)
            #listing of user created events
            @events = Event.find_by_sql("SELECT events.id, datetime, title from events INNER JOIN rsvps ON events.id = rsvps.event_id INNER JOIN event_user_data ON rsvps.id = event_user_data.rsvp_id WHERE event_user_data.user_role = 'owner' AND rsvps.email = '#{current_user.email}'")
            #listing of invited events
            @invited_events = Event.find_by_sql("SELECT events.id, datetime, title from events INNER JOIN rsvps ON events.id = rsvps.event_id INNER JOIN event_user_data ON rsvps.id = event_user_data.rsvp_id WHERE event_user_data.user_role = 'guest' AND rsvps.email = '#{current_user.email}'")
            #rsvp response
            @event_rsvp = EventUserDatum.find_by_sql("SELECT rsvp_id, attending from event_user_data INNER JOIN rsvps ON rsvps.id = event_user_data.rsvp_id INNER JOIN events ON events.id = rsvps.event_id  WHERE event_user_data.user_role = 'guest' AND rsvps.email = '#{current_user.email}'")
            #function of concat invited_events and event_rsvp to populate within a single table in views
            @max_length = [@invited_events, @event_rsvp].map(&:size).max
        else
            # sign in
        end
    end
  #end

  def show
    @user = User.find(current_user.id)
    @event = @user.events.find(params[:id])

    # if params[:user_id].to_i != @event.user.id
    # error
    # end
  end

  def new
    @event = Event.new
    @user = User.find(params[:user_id])
  end

  def edit
    @user = User.find(current_user.id)
    @event = @user.events.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @user = User.find(current_user.id)

    @event.save
    @user.events << @event

    #create entry in Rsvp model
    @rsvp = Rsvp.new(event_id: @user.events.last.id, user_id: current_user.id, name: current_user.username, email: current_user.email)
    @rsvp.save

    #create entry in event_user_datum model to link to rsvp model and state user_role as owner
    @eventuserdata = EventUserDatum.new(rsvp_id: @rsvp.id, user_role: :owner)
    @eventuserdata.save

    redirect_to user_events_path(@user)
  end

  def update
    @event = Event.find(params[:id])

    @event.update(event_params)
    redirect_to user_events_path(current_user.id)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_events_path(current_user.id)
  end

  def attendance
    @event = Event.find(params[:event_id])
    @event_user_data = @event.event_user_data.where(:attending => 'Yes')
  end

  def attendance_scanner
    @event = Event.find(params[:event_id])
  end

  def attendance_scan
    event = Event.find(params[:event_id])
    key = params[:key]
    rsvp = event.rsvps.find_by_key(key)
    if !rsvp.nil?
      rsvp.event_user_datum.update(:attended => true)
    end
    id = "edit_event_user_datum_" + rsvp.event_user_datum.id.to_s
    ActionCable.server.broadcast 'attendance_update_channel', { update: { id: id, attended: true } }
    head :ok, :content_type => 'text/html'
  end

  private

  def event_params
    params.require(:event).permit(:datetime, :title, user_ids: [])
  end
end

project3/app/helpers/events_helper.rb
module EventsHelper
end

project3/app/views/events/attendance.html.erb
<style>
	body {
		background-color: black;
		background-image: none;
	}
</style>
<div style="text-align:center;color:white;padding-top:2em">
	<h1>Attendance List</h1>
	<p class="attendance-statistics">Attendance: <span class="attendance-current">0</span> / <span class="attendance-total">0</span>, <span class="attendance-percentage">0</span>% present</p>
</div>
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Name</th>
				<th scope="col">Arrived</th>
			</tr>
		</thead>
		<tbody>
		<% @event_user_data.each_with_index do |e, i| %>
			<tr>
				<th scope="row"><%= i+1 %></th>
				<td><%= e.rsvp.user ? e.rsvp.user.username : e.rsvp.name %></td>
				<td><%= form_for e, url: events_users_datum_update_attendance_path(e), :remote => true, method: :patch do |f| %><%= f.check_box :attended, :onchange => "Rails.fire(this.form,'submit'); if (this.checked) {UI.attendanceCurrent.update(1)} else {UI.attendanceCurrent.update(-1)};", :class => "attended_checkbox" %><% end %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

<script>
	function UI() {
		
		this.createUIElement = function (name, DOMElement, updateFunc) {
			this[name] = {};
			this[name].element = DOMElement;
			this[name].value = 0;
			this[name].update = updateFunc;
		};
	
	};

	function addInt (delta) {
		this.value = parseInt(this.value) + delta;
		this.element.innerText = this.value;
		UI.attendancePercentage.update();
	};

	function calcAttendancePercentage() {
		total = UI.attendanceTotal.value;
		if (total === 0 ) return 0;
		current = UI.attendanceCurrent.value;
		this.value = +(Math.round((current / total) + "e+2") + "e-2") * 100;
		this.element.innerText = this.value;
	};

	UI = new UI();
	UI.createUIElement('attendanceCurrent', document.querySelector('.attendance-current'), addInt);
	UI.createUIElement('attendanceTotal', document.querySelector('.attendance-total'), addInt);
	UI.createUIElement('attendancePercentage', document.querySelector('.attendance-percentage'), calcAttendancePercentage);
	
	var forms = document.querySelectorAll('form[id^="edit_event_user_datum"]')
	
	forms.forEach(function (form) {
		UI.attendanceTotal.update(1)
		if (form.children[4].checked) {
			UI.attendanceCurrent.update(1)
		};
	});

</script>

project3/app/views/events/attendance_scanner.html.erb
<style>
  html, body {
    height: 100%;
    background: black;
  }

  #preview {
    width: 100%;
  }

  .wahlanthisbootstraplayoutcmilah {
    margin: 0 auto;
    width: 100%;
  }
</style>
  

<%= form_tag(event_attendance_scan_path(@event), id: "attendance-scanner", remote: true, method: :post) do %>
	<%= hidden_field_tag :key %>
<% end %>
<div class="wahlanthisbootstraplayoutcmilah">
  <video id="preview"></video>
</div>

<script>
  var QRScanner = {};

  function camStart() {

    QRScanner.scanner = new Instascan.Scanner({
      video: document.getElementById('preview'),
      scanPeriod: 5
    });
    
    function onDecode (content, image) {
      $('#key').val(content);
      Rails.fire($('#attendance-scanner')[0], 'submit');
    };

    QRScanner.scanner.addListener('scan', onDecode);
    
    Instascan.Camera.getCameras().then(function (cameras) {
      QRScanner.cameras = cameras;
      if (cameras.length > 0) {
        var last = cameras.length - 1;
        QRScanner.activeCameraId = cameras[last].id;
        QRScanner.scanner.start(cameras[last]);
        QRScanner.currentCameraNumber = last;
      } else {
        console.error('No cameras found.');
      }
    }).catch(function (e) {
      console.error(e);
    });

    QRScanner.camNext = function() {
      var last = this.cameras.length - 1;
      if (last === 0) return;
      if (this.currentCameraNumber === last) {
        this.currentCameraNumber = 0;
      } else {
        this.currentCameraNumber++;
      };
      this.scanner.start(this.cameras[this.currentCameraNumber]);
      this.activeCameraId = this.cameras[this.currentCameraNumber].id;
    };

  };

  camStart();
</script>

project3/app/views/events/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @event, local: true) do |form| %>

  <p>
    <%= form.label :datetime %><br>
    <%= form.datetime_field :datetime %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', user_events_path %>

project3/app/views/events/index.html.erb
<div class="container_index">
    <div class="row">
        <div class="events-grid-item1 col-sm-12">

          <h31>Events</h31>
   
                <table class="table table-hover">
                    <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Time</th>
                      <th scope="col">Title</th>
                      <th scope="col">Show</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Remove</th>
                      <th scope="col">RSVPs</th>
                      <th scope="col">Start</th>
                      <th scope="col">Scanner</th>
                    </tr>
                    </thead>
                    
                    <% @events.each do |event| %>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td><%= event.datetime%></td>
                        <td><%= event.title%></td>
                        <td><%= link_to 'Show', user_event_path(@user, event.id) %></td>
                        <td><%= link_to 'Edit', edit_user_event_path(@user, event.id) %></td>
                        <td><%= link_to 'Destroy', event_path(event.id),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
                        </td>
                        <td><%= link_to 'View', event_rsvps_path(event.id) %></td>
                        <td><%= link_to 'Start', user_event_attendance_list_path(current_user, event) %></td>
                        <td><%= link_to 'Scan', user_event_attendance_scanner_path(current_user, event) %></td>
                      </tr>
                    <% end %>
                    </tbody>
                </table>
                <div class="row-of-buttons">
                  <%= link_to 'Create Event', new_user_event_path(@user), :class => "btn btn-outline-light"%>
                  <%= link_to 'Back', user_path(@user), :class => "btn btn-outline-light" %>
                </div>

          <h1 class="section-2-title">Invited Event</h1>

                <table class="table table-hover">
                  <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Title</th>
                    <th scope="col">My RSVP</th>
                  </tr>
                  </thead>
                  
                  <% @max_length.times do |n| %>
                  <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td><%= @invited_events[n].try(:datetime) %></td>
                    <td><%= @invited_events[n].try(:title) %></td>
                    <% if @event_rsvp[n].try(:attending).blank? %>
                      <td><%= link_to 'Going', edit_event_rsvp_path(@invited_events[n].try(:id), @event_rsvp[n].try(:rsvp_id), attending: "yes") %> <%= link_to 'NotGoing', edit_event_rsvp_path(@invited_events[n].try(:id), @event_rsvp[n].try(:rsvp_id), attending: "no") %></td>
                    <% elsif @event_rsvp[n].try(:attending) == 'Yes' %>
                      <td><%= @event_rsvp[n].try(:attending) %></td>
                      <td><%= link_to 'Change RSVP?', edit_event_rsvp_path(@invited_events[n].try(:id), @event_rsvp[n].try(:rsvp_id), attending: "no") %></td>
                    <% else %>
                      <td><%= @event_rsvp[n].try(:attending) %></td>
                      <td><%= link_to 'Change RSVP?', edit_event_rsvp_path(@invited_events[n].try(:id), @event_rsvp[n].try(:rsvp_id), attending: "yes") %></td>
                    <% end %>
                  </tr>
                  <% end %>
                  </tbody>
                </table>
        </div>
    </div>    
</div>

project3/app/views/events/new.html.erb
<div class="container_new">
  <div class="row">
    <div class="registration-grid-item1 col-md-12">
        <h32>Your Event Date</h32>


            <%= form_with scope: :event, url: events_path, local: true do |form| %>
          
          <%#= form.hidden_field :user_ids, @user, :id %>
            <div class="form-group">
                <p>
                  <%= form.label :Date_Time %><br>
                  <%= form.datetime_field :datetime, :class => "form-control" %>
                </p>
            </div>
            <div class="form-group">
                <p>
                  <%= form.label :Title %><br>
                  <%= form.text_field :title, :class =>"form-control" %>
                </p>
            </div>    
                <p>
                  <%= form.submit "Submit", :class =>"btn btn-outline-light" %>
                </p>
                <p>
                  <%= link_to 'Back', user_path(@user), :class => "btn btn-outline-light" %>
                </p>
        <% end %>
    </div>
  </div>
</div>

project3/app/views/events/show.html.erb
<h1>Event</h1>

<p>
    <strong>DateTime: </strong>
    <%= @event.datetime %>
</p>

<p>
    <strong>Title: </strong>
    <%= @event.title %>
</p>

<%= link_to 'Edit', edit_user_event_path(@user, @event) %>
<%= link_to 'Back', user_events_path(current_user.id) %>